### ISSUE TITLE
Missing Release Agreement form for Train 40

### ISSUE THREAD

**Issue by JinlongYANG** [generalizable-neural-performer/gnr#1]
Hello,
Thanks for sharing the amazing work and dataset!
While I was trying to get access to the dataset, I couldn't find the release agreement form for Train 40 as mentioned in [gnr](https://github.com/generalizable-neural-performer/gnr)/[docs](https://github.com/generalizable-neural-performer/gnr/tree/main/docs)/Dataset.md 
Did I miss something?

**Comment by generalizable-neural-performer** [comment]
Hi Jinlong,

The release agreement now is available, and will sent you the download link no later than 2022.5.1 as long as your application email is recieved.

**Comment by JinlongYANG** [comment]
Thanks!
