### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by caiyongqi** [generalizable-neural-performer/gnr#10]
I can't install mesh_grid in the following environment:
pytorch: 1.9.1
cuda: 11.1.1
GPU: 3090

**Comment by generalizable-neural-performer** [comment]
Hi, @caiyongqi, it is recommended to replace the `AT_CHECK` to `TORCH_CHECK` [here](https://github.com/generalizable-neural-performer/gnr/blob/main/lib/mesh_grid/mesh_grid.cpp#L29), because `AT_CHECK` is deprecated after torch1.5. All other APIs are fine with the higher version of torch cpp.
