### ISSUE TITLE
Dataset of Test10 is missing

### ISSUE THREAD

**Issue by JinlongYANG** [generalizable-neural-performer/gnr#3]
Hi,

Thank you very much for sharing such amazing data with the community.
When I was trying to download the Test10 from dataset [webpage](https://generalizable-neural-performer.github.io/genebody.html), it said the link has been removed as following:
![image](https://user-images.githubusercontent.com/5700388/167682631-6757efab-aba9-4fc1-8f04-b26d5e1f7b07.png)
Is there any update regarding the Test10?

Best

**Comment by wywu** [comment]
Thanks for reminding, we will fix it!
Please try this link:
https://github.com/generalizable-neural-performer/gnr/blob/main/docs/Dataset.md#test10

**Comment by JinlongYANG** [comment]
Great, everything works!
Thanks for the quick response!
