### ISSUE TITLE
Issue with pre-trained model link

### ISSUE THREAD

**Issue by yyeboah** [generalizable-neural-performer/gnr#5]
First of all, thank you for the amazing work and the dataset accompanying this project. Looking forward to verifying the results and running into an issue retrieving the provided pre-trained weights using the associated Gdrive path. Could you kindly look into the issue?

**Comment by generalizable-neural-performer** [comment]
Hi, @yyeboah , I think there is some problem in gdown, you can try to download the weights from the [link](https://drive.google.com/file/d/17kVOpH4Hud-ZxKlvj0vbKB5dkIxwoHHm/view?usp=sharing), and put and extract it in `logs/genebody` manually. We will try to find a more convenient way to download the model.

**Comment by yyeboah** [comment]
@generalizable-neural-performer, The provided link works fine on my end. Thanks for addressing this issue promptly.
