### ISSUE TITLE
selected views and distortion

### ISSUE THREAD

**Issue by YuLiHN** [generalizable-neural-performer/gnr#6]
Hello!

Thanks for your incredible work!
I have two questions:
1. In the paper, you said only 4 views are given in the model for training, may I know which 4 views?
2. In dataset Test10, I found camera distortion parameters in the npy files. Do we need to undistort the images before using, or the images are already undistorted so distortion parameters can be ignored?

Thanks!

**Comment by SuX97** [comment]
Hi @YuLiHN :

Thanks for your question,

1. Four views are mutually orthogonal, specified [here](https://github.com/generalizable-neural-performer/gnr/blob/main/lib/data/GeneBodyDataset.py#L98)
2. Undistorting is needed for real-world captured data, and is performed [here](https://github.com/generalizable-neural-performer/gnr/blob/b572f807d1c1d5a673a2d414488c7c3418d342e9/lib/model/NeRFRenderer.py#L133)

**Comment by YuLiHN** [comment]
> Hi @YuLiHN :
> 
> Thanks for your question,
> 
> 1. Four views are mutually orthogonal, specified [here](https://github.com/generalizable-neural-performer/gnr/blob/main/lib/data/GeneBodyDataset.py#L98)
> 2. Undistorting is needed for real-world captured data, and is performed [here](https://github.com/generalizable-neural-performer/gnr/blob/b572f807d1c1d5a673a2d414488c7c3418d342e9/lib/model/NeRFRenderer.py#L133)

Thanks for your explanation!
