### ISSUE TITLE
recreate fitted smplx mesh from params in '/param' folder

### ISSUE THREAD

**Issue by shanemankiw** [generalizable-neural-performer/gnr#7]
In Annotation.md you mentioned that the mesh can be retrieved  by parameters in param folder. I noticed that the param npy files only contains the following information:
![image](https://user-images.githubusercontent.com/34244000/181191372-7484483a-96e9-46d5-ab3a-b6be81475e0c.png)
there are 135 joints, and a 66x1 pose provided. But it doesn't seem consistent with the smplx model. Could you explain how can we use the parameters in detail? Thank you very much in advance.

**Comment by generalizable-neural-performer** [comment]
Hi, @shanemankiw could you please provide the case name of this parameter? It seems like the very old version of smplx parameter dictionary structure. I am afraid there is some miss-alignment of the data version, if you can provide the download link, that will be better.

**Comment by shanemankiw** [comment]
> 

Hi, thanks for the quick reply. This is from Test10 dataset, and every param npy file in every person(amanda/param, joseph_mantanda/param, etc.) gave this type of parameters. For instance, this is from joseph_matanda/param/0400.npy
![image](https://user-images.githubusercontent.com/34244000/181219328-10e6d710-920a-4673-ac74-8da9453154b6.png)

**Comment by shanemankiw** [comment]
> Hi, @shanemankiw could you please provide the case name of this parameter? It seems like the very old version of smplx parameter dictionary structure. I am afraid there is some miss-alignment of the data version, if you can provide the download link, that will be better.

As for the download link, I downloaded directly from the onedrive link you provided.

**Comment by generalizable-neural-performer** [comment]
Hi, @shanemankiw , I am afraid that you downloaded data before 5.10 when we reframed data structure. Please re-download the Test10 data from the [link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/wchengad_connect_ust_hk/Er9_MPspGvpKlrFbVnmwnbEBloYJN7z9D0rP4Ms8LUcYKA).

**Comment by shanemankiw** [comment]
Oh that's true. Thanks for your reply!

**Comment by shanemankiw** [comment]
> Hi, @shanemankiw , I am afraid that you downloaded data before 5.10 when we reframed data structure. Please re-download the Test10 data from the [link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/wchengad_connect_ust_hk/Er9_MPspGvpKlrFbVnmwnbEBloYJN7z9D0rP4Ms8LUcYKA).

Hi, I visualized the bbox of the .obj mesh, keypoints3d from the param .npy,  along with the camera positions, and this happens:
![image](https://user-images.githubusercontent.com/34244000/181412019-2bd4758d-18cf-478f-b7ff-438c5ae2a9d0.png)
A closeup at bbox and body_pose:
![image](https://user-images.githubusercontent.com/34244000/181411935-54c188c0-1ae8-4c74-82a7-38557cd139ca.png)
The red box is the bbox calculated according to the .obj file, 
the yellow points are body_pose provided in param npy file.  
It seems like the body_pose does not match the mesh file, and also does not match with the camera positions. May I ask how can I transfer the body_pose&mesh to world coordinates?

And also, the scale is multiplied to the body pose already (smplx_scale=1 as provided in fuzhizhi/param/0409.npy)

**Comment by shanemankiw** [comment]
And F.Y.I, 'joints' in this version of data is consistent with world coordinate.
![image](https://user-images.githubusercontent.com/34244000/181453999-6eee7068-d61f-4916-b384-51168f97a357.png)

> > 
> 
> Hi, thanks for the quick reply. This is from Test10 dataset, and every param npy file in every person(amanda/param, joseph_mantanda/param, etc.) gave this type of parameters. For instance, this is from joseph_matanda/param/0400.npy ![image](https://user-images.githubusercontent.com/34244000/181219328-10e6d710-920a-4673-ac74-8da9453154b6.png)

**Comment by generalizable-neural-performer** [comment]
Please try to generate smpl mesh using the `smpl_from_param` function in [here](https://github.com/generalizable-neural-performer/gnr/blob/main/genebody/genebody.py#L189), to quickly check the difference between provided obj mesh and parameter generated mesh, please try 
```
python genebody/genebody.py path_to_genebody fuzhizhi path_to_smplx
```
`fuzhizhi.obj` will be generated in the project directory. 

For the bounding box issue, I can not find any misalignment, you can print the bounding box of mesh vertices and keypoints3d in parameter,  in the example of the data interface.

**Comment by shanemankiw** [comment]
> Please try to generate smpl mesh using the `smpl_from_param` function in [here](https://github.com/generalizable-neural-performer/gnr/blob/main/genebody/genebody.py#L189), to quickly check the difference between provided obj mesh and parameter generated mesh, please try
> 
> ```
> python genebody/genebody.py path_to_genebody fuzhizhi path_to_smplx
> ```
> 
> `fuzhizhi.obj` will be generated in the project directory.
> 
> For the bounding box issue, I can not find any misalignment, you can print the bounding box of mesh vertices and keypoints3d in parameter, in the example of the data interface.

Hi, i tried it and it seems like the joints from smpl output: 
output['joints'],
have a huge diffrence with 3dkeypoints from npy file:
param['keypoints3d'],
as shown here(green is smpl output, purple is keypoints3d):
![image](https://user-images.githubusercontent.com/34244000/181736045-ed9c4d09-52b9-4f12-b89b-2e93a82527f4.png)
but the mesh and bbox is good and fits in the world coordinates.

**Comment by generalizable-neural-performer** [comment]
Yes, have you tried the `genebody/genebody.py` scripts the validate the generated smpl keypoints? As mentioned in [Annotation.md](https://github.com/generalizable-neural-performer/gnr/blob/main/docs/Annotation.md#smplx-scale), we define a smpl scale 'outside' the smpl model, so all the output in 3d coordinate have to be multiplied by a scalar, both returned 'vertices' and 'joints'. 
Check out the reference code to get the aligned keypoints3d [here](https://github.com/generalizable-neural-performer/gnr/blob/main/genebody/genebody.py#L208).
