### ISSUE TITLE
Cannot reproduce the results in the paper

### ISSUE THREAD

**Issue by fuqianya** [generalizable-neural-performer/gnr#9]
Hi authors

Thanks for your great work! I am trying to reproduce the results in your paper (i.e., Table 2).
![1659147894(1)](https://user-images.githubusercontent.com/45023083/181866681-f2a6a359-0902-4b53-b202-1687bc706681.jpg)

I download the pretrained model from [here](https://drive.google.com/file/d/17kVOpH4Hud-ZxKlvj0vbKB5dkIxwoHHm/view?usp=sharing), and download the amanda.tar.gz and fuzhizhi.tar.gz from test data at [here](https://hkustconnect-my.sharepoint.com/:f:/g/personal/wchengad_connect_ust_hk/Er9_MPspGvpKlrFbVnmwnbEBloYJN7z9D0rP4Ms8LUcYKA?e=lnjS0N).
Then I evaluate the pretrained model with the following command:
```
python apps/run_genebody.py --config configs/test.txt --dataroot ${GENEBODY_ROOT}
```
However, I only get the following results which are inferior than the results in the Table 2
```
******
  2 amanda_0045_0
  3 lpips: 0.09362
  4 psnr: 22.27188
  5 ssim: 0.92902
  6 ------[total] lpips: 0.09362
  7 [total] psnr: 22.27188
  8 [total] ssim: 0.92902
  9 ******
 10 amanda_0060_0
 11 lpips: 0.09209
 12 psnr: 22.25502
 13 ssim: 0.93011
 14 ------[total] lpips: 0.09209
 15 [total] psnr: 22.25502
 16 [total] ssim: 0.93011
 17 ******
 18 amanda_0075_0
 19 lpips: 0.09473
 20 psnr: 21.96191
 21 ssim: 0.92794
 22 ------[total] lpips: 0.09473
 23 [total] psnr: 21.96191
 24 [total] ssim: 0.92794
 25 ******
...
 81 ******
 82 fuzhizhi_0400_0
 83 lpips: 0.10973
 84 psnr: 20.23185
 85 ssim: 0.87784
 86 ------[total] lpips: 0.10973
 87 [total] psnr: 20.23185
 88 [total] ssim: 0.87784
 89 ******
 90 fuzhizhi_0415_0
 91 lpips: 0.10417
 92 psnr: 20.62145
 93 ssim: 0.88344
 94 ------[total] lpips: 0.10417
 95 [total] psnr: 20.62145
 96 [total] ssim: 0.88344
 97 ******
 98 fuzhizhi_0430_0
 99 lpips: 0.10447
100 psnr: 20.55725
101 ssim: 0.88434
102 ------[total] lpips: 0.10447
103 [total] psnr: 20.55725
104 [total] ssim: 0.88434
105 ******
```
I wonder how can I get the results reported in the paper?

**Comment by generalizable-neural-performer** [comment]
Hi, your reported issue is reproduced by our team, we find the fallback on numbers is mainly due to the reframed version of our data on 5.12. We have updated the code and data, please update the genebody data and gnr pretrained model using our new download tool.

The number of this version can be aligned with the implementation in [openxrlab/xrnerf](https://github.com/openxrlab/xrnerf/blob/main/docs/en/benchmark.md#gnr).
